version: '3'
services:
    database:
        build: 
            context: ./dockerfilebd
            dockerfile: Dockerfile
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_DATABASE: Joruma02
            MYSQL_USER: joan
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            # - mysql_data:/var/lib/mysql
            - ./db/Joruma02.sql:/docker-entrypoint-initdb.d/Joruma02.sql

        networks:
            - mynetwork

    web:    
        build: 
            context: ./dockfileweb
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - mynetwork

    adminphp:
        build: 
            context: ./dockerfilephp
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        environment:
          PMA_HOST: database
          PMA_USER: joan
          PMA_PASSWORD: root
          PMA_PORT: 3306
        networks:
            - mynetwork

networks:
    mynetwork:

volumes:
    mysql_data:
